name: test branch creation 
# This bumps the version, updates the changelogs, publishes a GitHub release, and publishes the packages to npm.

# Package publishing is manually triggered on github actions dashboard
on: pull_request

jobs:
  deploy:
    name: 'Publish new version of public packages'
    environment: npm deploy
    timeout-minutes: 15
    runs-on: ubuntu-latest-16-cores-open

    steps:
      - name: Generate GH token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.HUPPY_APP_ID }}
          private_key: ${{ secrets.HUPPY_APP_PRIVATE_KEY }}

      - name: Check out code
        uses: actions/checkout@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: Run our setup
        uses: ./.github/actions/setup

      - name: Publish
        run: |
          git config --global user.name 'huppy-bot[bot]'
          git config --global user.email '128400622+huppy-bot[bot]@users.noreply.github.com'
          git push origin v2.0.0:refs/heads/v2.0.x

